# Use a CUDA-enabled base image
FROM nvidia/cuda:11.0-base
# Set the working directory
WORKDIR /app
# Install any CPU-specific dependencies (if applicable)
COPY requirements_cpu.txt .
RUN pip install -r requirements_cpu.txt
# Install GPU-specific dependencies
COPY requirements_gpu.txt .
RUN pip install -r requirements_gpu.txt
# Copy your code into the image
COPY . .
# Set the execution command
CMD ["python", "step3_calc_focmec_init.py"]
CMD ["python", "step4_calc_focmec_refoc.py"]
